### ISSUE TITLE
Potential missing rule: early pick-up of pile

### ISSUE THREAD

**Issue by amogower** [aod/zhithead#2]
Loving your work so far! It's a really smooth experience and great fun to play around with.

I'm not sure if this is an official rule, but I've always played with the ability to pick up the pile at will, rather than having to play through until you can't play any more cards.

**Comment by aod** [comment]
Hi, first of all thanks for the kind words!

The funny thing is, my friend and I recently had a discussion about this exact issue. He pointed the same thing out you did. The times I played with him I always used to play a card whenever I could. I just found out that he didn't and often picked up the pile instead.

Anyways, your comment only further confirms that this should be allowed 😁
